# Jasypt Config
jasypt:
    encryptor:
        bean: jasyptEncryptor
        password : jasypt

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ENC(fxZWbZrQVJ2M0Lu3dD4SPAHVPtAESrtyEPsQvnyMRjB1AlBQ4f/Y84IN0E0mV3xbYDxMaM7essE=)
        username: ENC(ht2MlxVPcmNxG4KsuXI0zQ==)
        password: ENC(esd5Cn4+oi13KBCzy96fag8Q3XQII9L2)
        column:
            encrypt:
                    key: ENC(vSpSQWvDSsZn/3yVCbkE51/NMgE/iB2FLVbYoiSvgdgPYPiNNXMcprpH5FXYWC0+)

    jpa:
        hibernate:
            ddl-auto: update

    thymeleaf:
        encoding: UTF-8
        prefix: classpath:/templates/
        cache: 'false'
        suffix: .html
        template-mode: LEGACYHTML5
        mode: HTML
        dialects: thymeleaf.extras.fragments.dialect.FragmentLayoutDialect

    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
        freemarker:
            cache: false
        thymeleaf:
            cache: false

    mail:
        host: smtp.gmail.com
        port: 587
        username: todaycoding1015@gmail.com
        password: ENC(W6ZJEI7h3P4Up0PUBsw7ej8xwWnPdFXv//N2KERc2tM=)
        properties:
          mail:
              smtp:
                  auth: true
                  starttls:
                      enable: true

jwt:
    header: Authorization
    secret: ENC(6W9FeN7Ec2gV813Og8eJJ3pXxs4OrJvl/YU6W8r/HwGZ1xtPxpnfFzBc9qyDdd6o62gdbWYLgKlbFvDdTZCHrQ==)
    tokenValidTime: 86400


